name: Update price

on:
  schedule:
    - cron: "0 * * * *"   # svaki sat
  workflow_dispatch:

permissions:
  contents: write 

jobs:
  scrape:
    runs-on: ubuntu-latest
    env:
      EMAIL_USER: ${{ secrets.EMAIL_USER }}
      EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      EMAIL_TO:   ${{ secrets.EMAIL_TO }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
      - run: pip install requests
      - run: python scrape_bplatz.py
      - name: Commit prices.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add prices.json
          git commit -m "Update price" || echo "No changes"
          git push
